// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfLWPgoTi6v8BQKHRdUcGKVnRSCXaUGeY',
    appId: '1:344728487984:web:9d62b71bde53cb7b4b45f5',
    messagingSenderId: '344728487984',
    projectId: 'village-connect-26949',
    authDomain: 'village-connect-26949.firebaseapp.com',
    storageBucket: 'village-connect-26949.firebasestorage.app',
    measurementId: 'G-LG8F6J9QR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbpnL1xJEvHsOb4zKe0_nZFaEvO08d0wY',
    appId: '1:344728487984:android:98650dda1c6739524b45f5',
    messagingSenderId: '344728487984',
    projectId: 'village-connect-26949',
    storageBucket: 'village-connect-26949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkNW50y64Pd49Ti-Do8DBvIGjrlNRiIw',
    appId: '1:344728487984:ios:837e3ebeab5b212a4b45f5',
    messagingSenderId: '344728487984',
    projectId: 'village-connect-26949',
    storageBucket: 'village-connect-26949.firebasestorage.app',
    iosBundleId: 'com.example.villageConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkNW50y64Pd49Ti-Do8DBvIGjrlNRiIw',
    appId: '1:344728487984:ios:837e3ebeab5b212a4b45f5',
    messagingSenderId: '344728487984',
    projectId: 'village-connect-26949',
    storageBucket: 'village-connect-26949.firebasestorage.app',
    iosBundleId: 'com.example.villageConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfLWPgoTi6v8BQKHRdUcGKVnRSCXaUGeY',
    appId: '1:344728487984:web:080f0581de1591f64b45f5',
    messagingSenderId: '344728487984',
    projectId: 'village-connect-26949',
    authDomain: 'village-connect-26949.firebaseapp.com',
    storageBucket: 'village-connect-26949.firebasestorage.app',
    measurementId: 'G-LJQBFFJDRY',
  );

}