import 'package:flutter/widgets.dart';

class VcCopy {
  const VcCopy(this.languageCode);

  factory VcCopy.of(BuildContext context) {
    return VcCopy(Localizations.localeOf(context).languageCode);
  }

  final String languageCode;

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'chooseLanguage': 'Choose your preferred language',
      'languageIntro': 'Use Village Connect in Sinhala, Tamil, or English.',
      'continue': 'Continue',
      'officialPortal': 'Official citizen portal',
      'loginTitle': 'Welcome Back',
      'loginSubtitle': 'Sign in with your NIC number or email address.',
      'nicOrEmail': 'NIC Number or Email',
      'nicHint': 'Enter NIC or email',
      'password': 'Password',
      'passwordHint': 'Enter your password',
      'firstTime': 'First time accessing?',
      'firstTimeBody':
          'Your GN officer creates your account and sends credentials by email.',
      'home': 'Home',
      'requests': 'Requests',
      'community': 'Community',
      'profile': 'Profile',
      'notices': 'Notices',
      'goodMorning': 'Good morning',
      'goodAfternoon': 'Good afternoon',
      'goodEvening': 'Good evening',
      'gnDivision': 'GN division',
      'activeRequests': 'Active requests',
      'latestRequest': 'My Latest Request',
      'quickServices': 'Quick Services',
      'noticeBoard': 'Notice Board',
      'lostFound': 'Lost & Found',
      'requestCertificate': 'Request Certificate',
      'jobs': 'Community Jobs',
      'trackRequests': 'Track Requests',
      'emergency': 'Report Emergency',
      'noRequests': 'No requests yet',
      'submitFirst': 'Submit your first certificate request.',
      'applications': 'Applications',
      'searchApplications': 'Search applications',
      'trackProgress': 'Track Application Progress',
      'trackProgressBody': 'See current status and GN updates.',
      'apply': 'Apply',
      'details': 'Form Details',
      'requiredDetails': 'Required details for GN submission',
      'all': 'All',
      'searchNotices': 'Search notices',
      'official': 'Official',
      'readMore': 'Read More',
      'noNotices': 'Check back later',
      'noNoticesBody': 'GN Officer will post notices here.',
      'communityTitle': 'Community Feed',
      'communitySubtitle': 'Approved village posts for jobs and lost items.',
      'addPost': 'Add Post',
      'moderation': 'Moderation',
      'approvedFeed': 'Approved Feed',
      'noPosts': 'Nothing here yet',
      'noPostsBody': 'Be the first to post for your village.',
    },
    'si': {
      'chooseLanguage': 'ඔබ කැමති භාෂාව තෝරන්න',
      'languageIntro':
          'Village Connect සිංහල, தமிழ் හෝ English භාෂාවෙන් භාවිත කරන්න.',
      'continue': 'ඉදිරියට',
      'officialPortal': 'නිල පුරවැසි සේවා ද්වාරය',
      'loginTitle': 'නැවත සාදරයෙන් පිළිගනිමු',
      'loginSubtitle':
          'ඔබගේ ජාතික හැඳුනුම්පත් අංකය හෝ ඊමේල් ලිපිනයෙන් පිවිසෙන්න.',
      'nicOrEmail': 'ජා.හැ.අංකය හෝ ඊමේල්',
      'nicHint': 'ජා.හැ.අංකය හෝ ඊමේල් ඇතුළත් කරන්න',
      'password': 'මුරපදය',
      'passwordHint': 'ඔබගේ මුරපදය ඇතුළත් කරන්න',
      'firstTime': 'පළමු වරට පිවිසෙනවාද?',
      'firstTimeBody':
          'ඔබගේ GN නිලධාරියා ගිණුම සකස් කර පිවිසුම් තොරතුරු ඊමේල් මඟින් යවයි.',
      'home': 'මුල් පිටුව',
      'requests': 'ඉල්ලීම්',
      'community': 'ප්‍රජාව',
      'profile': 'පැතිකඩ',
      'notices': 'දැන්වීම්',
      'goodMorning': 'සුභ උදෑසනක්',
      'goodAfternoon': 'සුභ දහවලක්',
      'goodEvening': 'සුභ සන්ධ්‍යාවක්',
      'gnDivision': 'GN කොට්ඨාසය',
      'activeRequests': 'සක්‍රීය ඉල්ලීම්',
      'latestRequest': 'මගේ නවතම ඉල්ලීම',
      'quickServices': 'ඉක්මන් සේවා',
      'noticeBoard': 'දැන්වීම් පුවරුව',
      'lostFound': 'අස්ථානගත හා සොයාගත්',
      'requestCertificate': 'සහතික ඉල්ලීම',
      'jobs': 'ප්‍රජා රැකියා',
      'trackRequests': 'ඉල්ලීම් ලුහුබඳින්න',
      'emergency': 'හදිසි තත්ත්වය වාර්තා කරන්න',
      'noRequests': 'තවම ඉල්ලීම් නොමැත',
      'submitFirst': 'ඔබගේ පළමු සහතික ඉල්ලීම යොමු කරන්න.',
      'applications': 'අයදුම්පත්',
      'searchApplications': 'අයදුම්පත් සොයන්න',
      'trackProgress': 'අයදුම්පත් ප්‍රගතිය',
      'trackProgressBody': 'වත්මන් තත්ත්වය සහ GN යාවත්කාලීන බලන්න.',
      'apply': 'අයදුම් කරන්න',
      'details': 'පෝරම විස්තර',
      'requiredDetails': 'GN ඉදිරිපත් කිරීම සඳහා අවශ්‍ය විස්තර',
      'all': 'සියල්ල',
      'searchNotices': 'දැන්වීම් සොයන්න',
      'official': 'නිල',
      'readMore': 'තව කියවන්න',
      'noNotices': 'පසුව නැවත බලන්න',
      'noNoticesBody': 'GN නිලධාරියා දැන්වීම් මෙහි පළ කරයි.',
      'communityTitle': 'ප්‍රජා පෝෂණය',
      'communitySubtitle': 'රැකියා සහ අස්ථානගත දෑ සඳහා අනුමත ගම් දැන්වීම්.',
      'addPost': 'දැන්වීමක් එක් කරන්න',
      'moderation': 'මධ්‍යස්ථකරණය',
      'approvedFeed': 'අනුමත දැන්වීම්',
      'noPosts': 'තවම කිසිවක් නැත',
      'noPostsBody': 'ඔබගේ ගමට පළමු දැන්වීම එක් කරන්න.',
    },
    'ta': {
      'chooseLanguage': 'உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்',
      'languageIntro':
          'Village Connect-ஐ தமிழ், සිංහල அல்லது English-ல் பயன்படுத்தவும்.',
      'continue': 'தொடரவும்',
      'officialPortal': 'அதிகாரப்பூர்வ குடிமக்கள் சேவை வாயில்',
      'loginTitle': 'மீண்டும் வரவேற்கிறோம்',
      'loginSubtitle':
          'உங்கள் தேசிய அடையாள அட்டை எண் அல்லது மின்னஞ்சல் மூலம் உள்நுழையவும்.',
      'nicOrEmail': 'தே.அ.அ எண் அல்லது மின்னஞ்சல்',
      'nicHint': 'தே.அ.அ எண் அல்லது மின்னஞ்சலை உள்ளிடவும்',
      'password': 'கடவுச்சொல்',
      'passwordHint': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      'firstTime': 'முதல் முறையா?',
      'firstTimeBody':
          'உங்கள் GN அதிகாரி கணக்கை உருவாக்கி உள்நுழைவு தகவலை மின்னஞ்சலில் அனுப்புவார்.',
      'home': 'முகப்பு',
      'requests': 'கோரிக்கைகள்',
      'community': 'சமூகம்',
      'profile': 'சுயவிவரம்',
      'notices': 'அறிவிப்புகள்',
      'goodMorning': 'காலை வணக்கம்',
      'goodAfternoon': 'மதிய வணக்கம்',
      'goodEvening': 'மாலை வணக்கம்',
      'gnDivision': 'GN பிரிவு',
      'activeRequests': 'செயலில் உள்ள கோரிக்கைகள்',
      'latestRequest': 'என் சமீபத்திய கோரிக்கை',
      'quickServices': 'விரைவு சேவைகள்',
      'noticeBoard': 'அறிவிப்பு பலகை',
      'lostFound': 'இழந்தது & கண்டது',
      'requestCertificate': 'சான்றிதழ் கோரிக்கை',
      'jobs': 'சமூக வேலைகள்',
      'trackRequests': 'கோரிக்கைகளை கண்காணி',
      'emergency': 'அவசரநிலை தெரிவி',
      'noRequests': 'இன்னும் கோரிக்கைகள் இல்லை',
      'submitFirst': 'உங்கள் முதல் சான்றிதழ் கோரிக்கையை சமர்ப்பிக்கவும்.',
      'applications': 'விண்ணப்பங்கள்',
      'searchApplications': 'விண்ணப்பங்களைத் தேடுக',
      'trackProgress': 'விண்ணப்ப முன்னேற்றம்',
      'trackProgressBody':
          'தற்போதைய நிலை மற்றும் GN புதுப்பிப்புகளைப் பார்க்கவும்.',
      'apply': 'விண்ணப்பிக்க',
      'details': 'படிவ விவரங்கள்',
      'requiredDetails': 'GN சமர்ப்பிப்பிற்கு தேவையான விவரங்கள்',
      'all': 'அனைத்தும்',
      'searchNotices': 'அறிவிப்புகளைத் தேடுக',
      'official': 'அதிகாரப்பூர்வம்',
      'readMore': 'மேலும் வாசிக்க',
      'noNotices': 'பின்னர் பார்க்கவும்',
      'noNoticesBody': 'GN அதிகாரி அறிவிப்புகளை இங்கே வெளியிடுவார்.',
      'communityTitle': 'சமூக ஊட்டம்',
      'communitySubtitle':
          'வேலைகள் மற்றும் இழந்த பொருட்களுக்கு அங்கீகரிக்கப்பட்ட கிராம பதிவுகள்.',
      'addPost': 'பதிவு சேர்க்க',
      'moderation': 'மதிப்பாய்வு',
      'approvedFeed': 'அங்கீகரிக்கப்பட்ட பதிவுகள்',
      'noPosts': 'இன்னும் எதுவும் இல்லை',
      'noPostsBody': 'உங்கள் கிராமத்திற்கான முதல் பதிவைச் சேர்க்கவும்.',
    },
  };

  String t(String key) => _values[languageCode]?[key] ?? _values['en']![key]!;
}
